/**
 * Created by LastBerserk on 28.01.2020.
 */


export default {
    SKILL_ACROBATICS_RANKS: "r_acrob",
    SKILL_APPRAISE_RANKS: "r_appraise",
    SKILL_BLUFF_RANKS: "r_bluff",
    SKILL_CLIMB_RANKS: "r_climb",
    SKILL_CRAFT_RANKS: "r_craft",
    SKILL_DIPLOMACY_RANKS: "r_diplo",
    SKILL_DISABLE_DEVICE_RANKS: "r_disab",
    SKILL_DISGUISE_RANKS: "r_disgu",
    SKILL_ESCAPE_ARTIST_RANKS: "r_escap",
    SKILL_FLY_RANKS: "r_fly",
    SKILL_HANDLE_ANIMAL_RANKS: "r_handl",
    SKILL_HEAL_RANKS: "r_heal",
    SKILL_INTIMIDATE_RANKS: "r_intim",
    SKILL_LINGUISTICS_RANKS: "r_lingu",
    SKILL_PERCEPTION_RANKS: "r_perce",
    SKILL_PERFORM_RANKS: "r_perfor",
    SKILL_PROFESSION_RANKS: "r_profe",
    SKILL_RIDE_RANKS: "r_ride",
    SKILL_SENSE_MOTIVE_RANKS: "r_sense",
    SKILL_SLEIGHT_OF_HAND_RANKS: "r_sleight",
    SKILL_SPELLCRAFT_RANKS: "r_spell",
    SKILL_STEALTH_RANKS: "r_stealth",
    SKILL_SURVIVAL_RANKS: "r_survival",
    SKILL_SWIM_RANKS: "r_swim",
    SKILL_USE_MAGIC_DEVICE_RANKS: "r_magic",

    SKILL_KNOWLEDGE_ARCANA_RANKS: "r_arcana",
    SKILL_KNOWLEDGE_DUNGEONEERING_RANKS: "r_dungeon",
    SKILL_KNOWLEDGE_ENGINEERING_RANKS: "r_engin",
    SKILL_KNOWLEDGE_GEOGRAPHY_RANKS: "r_geogr",
    SKILL_KNOWLEDGE_HISTORY_RANKS: "r_history",
    SKILL_KNOWLEDGE_LOCAL_RANKS: "r_local",
    SKILL_KNOWLEDGE_NATURE_RANKS: "r_nature",
    SKILL_KNOWLEDGE_NOBILITY_RANKS: "r_nobil",
    SKILL_KNOWLEDGE_PLANES_RANKS: "r_planes",
    SKILL_KNOWLEDGE_RELIGION_RANKS: "r_religion",

    SKILL_ACROBATICS: "s_acrob",
    SKILL_APPRAISE: "s_appraise",
    SKILL_BLUFF: "s_bluff",
    SKILL_CLIMB: "s_climb",
    SKILL_CRAFT: "s_craft",
    SKILL_DIPLOMACY: "s_diplo",
    SKILL_DISABLE_DEVICE: "s_disab",
    SKILL_DISGUISE: "s_disgu",
    SKILL_ESCAPE_ARTIST: "s_escap",
    SKILL_FLY: "s_fly",
    SKILL_HANDLE_ANIMAL: "s_handl",
    SKILL_HEAL: "s_heal",
    SKILL_INTIMIDATE: "s_intim",
    SKILL_LINGUISTICS: "s_lingu",
    SKILL_PERCEPTION: "s_perce",
    SKILL_PERFORM: "s_perfor",
    SKILL_PROFESSION: "s_profe",
    SKILL_RIDE: "s_ride",
    SKILL_SENSE_MOTIVE: "s_sense",
    SKILL_SLEIGHT_OF_HAND: "s_sleight",
    SKILL_SPELLCRAFT: "s_spell",
    SKILL_STEALTH: "s_stealth",
    SKILL_SURVIVAL: "s_survival",
    SKILL_SWIM: "s_swim",
    SKILL_USE_MAGIC_DEVICE: "s_magic",

    SKILL_KNOWLEDGE_ARCANA: "s_arcana",
    SKILL_KNOWLEDGE_DUNGEONEERING: "s_dungeon",
    SKILL_KNOWLEDGE_ENGINEERING: "s_engin",
    SKILL_KNOWLEDGE_GEOGRAPHY: "s_geogr",
    SKILL_KNOWLEDGE_HISTORY: "s_history",
    SKILL_KNOWLEDGE_LOCAL: "s_local",
    SKILL_KNOWLEDGE_NATURE: "s_nature",
    SKILL_KNOWLEDGE_NOBILITY: "s_nobil",
    SKILL_KNOWLEDGE_PLANES: "s_planes",
    SKILL_KNOWLEDGE_RELIGION: "s_religion",

    CLASS_SKILLS_ARRAY: "c_skills_array",

    SKILL_SCIENCE_RANKS: "r_science",
    SKILL_SCIENCE: "s_science"
};